spring:
  application:
    name: "gatewayserver"

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  config:
    import: "optional:configserver:http://localhost:8071"

  rabbitmq:
    host: "localhost"
    port: "5672"
    username: "guest"
    password: "guest"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Microservices API Gateway Server"
    version: "1.0.0"
